name: Deploy Logic App
# on: workflow_dispatch 
on:
  push:
    branches:
        - main
    paths:
        - '**.json'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    #Log into Azure
    - uses: azure/login@v1
      with:
           creds: '{"clientId":"${{ secrets.ACTION_SPN_CLIENTID }}","clientSecret":"${{ secrets.ACTION_SPN_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    # Deploy Logic App ARM Template
    - name: deploy-re-statements
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: 'rg-aiml'
        deploymentName: 'logicapp_doci_restatement_deployment'
        template: 'logicapp-formrecognizer/logicapp-formrecognizer/LogicApp.json'
        parameters: 'logicapp-formrecognizer/logicapp-formrecognizer/LogicApp.parameters.json'
        failOnStdErr: false

    - name: deploy-sec-form10q
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: 'rg-aiml'
        deploymentName: 'logicapp_doci_form10q_deployment'
        template: 'logicapp-formrecognizer/logicapp-formrecognizer/LogicApp.json'
        parameters: 'logicapp-formrecognizer/logicapp-formrecognizer/LogicApp.SECForm10q.parameters.json'
        failOnStdErr: false        
